package engine

import (
	model "gitlab.com/paramountdax-exchange/exchange_api_v2/data"
)

// Event structure for order execution
type Event struct {
	Order  model.Order
	Events []model.Event
}

// Decode from binary
func (event *Event) DecodeFromBinary(val []byte) {
	_ = event.Order.FromBinary(val)
}

// SetEvents - sets the generated events from that order on the current market
func (event *Event) SetEvents(events []model.Event) {
	event.Events = events
}

// HasEvents checks if there are any events generated by the order.
// @deprecated should always be true since the order is acknowledged
func (event Event) HasEvents() bool {
	return len(event.Events) > 0
}
