// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: referral_earnings.proto

package referral_earnings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelatedObjectType int32

const (
	// Invalid status for any non set field
	RelatedObjectType_None          RelatedObjectType = 0
	RelatedObjectType_BonusContract RelatedObjectType = 1
)

// Enum value maps for RelatedObjectType.
var (
	RelatedObjectType_name = map[int32]string{
		0: "None",
		1: "BonusContract",
	}
	RelatedObjectType_value = map[string]int32{
		"None":          0,
		"BonusContract": 1,
	}
)

func (x RelatedObjectType) Enum() *RelatedObjectType {
	p := new(RelatedObjectType)
	*p = x
	return p
}

func (x RelatedObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelatedObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_referral_earnings_proto_enumTypes[0].Descriptor()
}

func (RelatedObjectType) Type() protoreflect.EnumType {
	return &file_referral_earnings_proto_enumTypes[0]
}

func (x RelatedObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelatedObjectType.Descriptor instead.
func (RelatedObjectType) EnumDescriptor() ([]byte, []int) {
	return file_referral_earnings_proto_rawDescGZIP(), []int{0}
}

type AddReferralEarningsFromUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelatedObjectType RelatedObjectType `protobuf:"varint,1,opt,name=RelatedObjectType,proto3,enum=referral_earnings.RelatedObjectType" json:"RelatedObjectType,omitempty"`
	RelatedObjectId   uint64            `protobuf:"varint,2,opt,name=RelatedObjectId,proto3" json:"RelatedObjectId,omitempty"`
	UserId            uint64            `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Amount            uint64            `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	CoinSymbol        string            `protobuf:"bytes,5,opt,name=CoinSymbol,proto3" json:"CoinSymbol,omitempty"`
	RefId             string            `protobuf:"bytes,6,opt,name=RefId,proto3" json:"RefId,omitempty"`
}

func (x *AddReferralEarningsFromUser) Reset() {
	*x = AddReferralEarningsFromUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_referral_earnings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReferralEarningsFromUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReferralEarningsFromUser) ProtoMessage() {}

func (x *AddReferralEarningsFromUser) ProtoReflect() protoreflect.Message {
	mi := &file_referral_earnings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReferralEarningsFromUser.ProtoReflect.Descriptor instead.
func (*AddReferralEarningsFromUser) Descriptor() ([]byte, []int) {
	return file_referral_earnings_proto_rawDescGZIP(), []int{0}
}

func (x *AddReferralEarningsFromUser) GetRelatedObjectType() RelatedObjectType {
	if x != nil {
		return x.RelatedObjectType
	}
	return RelatedObjectType_None
}

func (x *AddReferralEarningsFromUser) GetRelatedObjectId() uint64 {
	if x != nil {
		return x.RelatedObjectId
	}
	return 0
}

func (x *AddReferralEarningsFromUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddReferralEarningsFromUser) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddReferralEarningsFromUser) GetCoinSymbol() string {
	if x != nil {
		return x.CoinSymbol
	}
	return ""
}

func (x *AddReferralEarningsFromUser) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

var File_referral_earnings_proto protoreflect.FileDescriptor

var file_referral_earnings_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x5f, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x61, 0x6c, 0x5f, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x81, 0x02, 0x0a,
	0x1b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x45, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x11,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72,
	0x61, 0x6c, 0x5f, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f,
	0x69, 0x6e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x43, 0x6f, 0x69, 0x6e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65,
	0x66, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x66, 0x49, 0x64,
	0x2a, 0x30, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x10, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2e, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61,
	0x6c, 0x5f, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_referral_earnings_proto_rawDescOnce sync.Once
	file_referral_earnings_proto_rawDescData = file_referral_earnings_proto_rawDesc
)

func file_referral_earnings_proto_rawDescGZIP() []byte {
	file_referral_earnings_proto_rawDescOnce.Do(func() {
		file_referral_earnings_proto_rawDescData = protoimpl.X.CompressGZIP(file_referral_earnings_proto_rawDescData)
	})
	return file_referral_earnings_proto_rawDescData
}

var file_referral_earnings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_referral_earnings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_referral_earnings_proto_goTypes = []interface{}{
	(RelatedObjectType)(0),              // 0: referral_earnings.RelatedObjectType
	(*AddReferralEarningsFromUser)(nil), // 1: referral_earnings.AddReferralEarningsFromUser
}
var file_referral_earnings_proto_depIdxs = []int32{
	0, // 0: referral_earnings.AddReferralEarningsFromUser.RelatedObjectType:type_name -> referral_earnings.RelatedObjectType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_referral_earnings_proto_init() }
func file_referral_earnings_proto_init() {
	if File_referral_earnings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_referral_earnings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReferralEarningsFromUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_referral_earnings_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_referral_earnings_proto_goTypes,
		DependencyIndexes: file_referral_earnings_proto_depIdxs,
		EnumInfos:         file_referral_earnings_proto_enumTypes,
		MessageInfos:      file_referral_earnings_proto_msgTypes,
	}.Build()
	File_referral_earnings_proto = out.File
	file_referral_earnings_proto_rawDesc = nil
	file_referral_earnings_proto_goTypes = nil
	file_referral_earnings_proto_depIdxs = nil
}
