// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: order_canceled_confirmation.proto

package order_canceled_confirmation

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderCanceledStatus int32

const (
	// OK is used when the order was cancelled by the matching engine
	OrderCanceledStatus_OK                 OrderCanceledStatus = 0 // FromME
	OrderCanceledStatus_InvalidOrderFromME OrderCanceledStatus = 1
	OrderCanceledStatus_CancelFailedFromME OrderCanceledStatus = 2
	OrderCanceledStatus_AlreadyFilled      OrderCanceledStatus = 3
	OrderCanceledStatus_AlreadyCancelled   OrderCanceledStatus = 4
	OrderCanceledStatus_SendingFailed      OrderCanceledStatus = 5
	OrderCanceledStatus_CancelFailed       OrderCanceledStatus = 6
	OrderCanceledStatus_Timeout            OrderCanceledStatus = 7
)

// Enum value maps for OrderCanceledStatus.
var (
	OrderCanceledStatus_name = map[int32]string{
		0: "OK",
		1: "InvalidOrderFromME",
		2: "CancelFailedFromME",
		3: "AlreadyFilled",
		4: "AlreadyCancelled",
		5: "SendingFailed",
		6: "CancelFailed",
		7: "Timeout",
	}
	OrderCanceledStatus_value = map[string]int32{
		"OK":                 0,
		"InvalidOrderFromME": 1,
		"CancelFailedFromME": 2,
		"AlreadyFilled":      3,
		"AlreadyCancelled":   4,
		"SendingFailed":      5,
		"CancelFailed":       6,
		"Timeout":            7,
	}
)

func (x OrderCanceledStatus) Enum() *OrderCanceledStatus {
	p := new(OrderCanceledStatus)
	*p = x
	return p
}

func (x OrderCanceledStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCanceledStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_canceled_confirmation_proto_enumTypes[0].Descriptor()
}

func (OrderCanceledStatus) Type() protoreflect.EnumType {
	return &file_order_canceled_confirmation_proto_enumTypes[0]
}

func (x OrderCanceledStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCanceledStatus.Descriptor instead.
func (OrderCanceledStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_canceled_confirmation_proto_rawDescGZIP(), []int{0}
}

type OrderCanceledConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the name of the action that it should execute
	Event string `protobuf:"bytes,1,opt,name=Event,proto3" json:"Event,omitempty"`
	// each generated event should be unique
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// Order ID
	OrderId uint64 `protobuf:"varint,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	// order cancelled status
	Status OrderCanceledStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=order_canceled_confirmation.OrderCanceledStatus" json:"Status,omitempty"`
	// why order not cancelled
	ErrorMsg string `protobuf:"bytes,5,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
}

func (x *OrderCanceledConfirmation) Reset() {
	*x = OrderCanceledConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_canceled_confirmation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCanceledConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCanceledConfirmation) ProtoMessage() {}

func (x *OrderCanceledConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_order_canceled_confirmation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCanceledConfirmation.ProtoReflect.Descriptor instead.
func (*OrderCanceledConfirmation) Descriptor() ([]byte, []int) {
	return file_order_canceled_confirmation_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCanceledConfirmation) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *OrderCanceledConfirmation) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *OrderCanceledConfirmation) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCanceledConfirmation) GetStatus() OrderCanceledStatus {
	if x != nil {
		return x.Status
	}
	return OrderCanceledStatus_OK
}

func (x *OrderCanceledConfirmation) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_order_canceled_confirmation_proto protoreflect.FileDescriptor

var file_order_canceled_confirmation_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xc1, 0x01, 0x0a, 0x19, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x48,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x2a, 0xa8, 0x01, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d,
	0x4d, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x46,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x6c, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x04, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x05,
	0x12, 0x10, 0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x07, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_canceled_confirmation_proto_rawDescOnce sync.Once
	file_order_canceled_confirmation_proto_rawDescData = file_order_canceled_confirmation_proto_rawDesc
)

func file_order_canceled_confirmation_proto_rawDescGZIP() []byte {
	file_order_canceled_confirmation_proto_rawDescOnce.Do(func() {
		file_order_canceled_confirmation_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_canceled_confirmation_proto_rawDescData)
	})
	return file_order_canceled_confirmation_proto_rawDescData
}

var file_order_canceled_confirmation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_canceled_confirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_canceled_confirmation_proto_goTypes = []interface{}{
	(OrderCanceledStatus)(0),          // 0: order_canceled_confirmation.OrderCanceledStatus
	(*OrderCanceledConfirmation)(nil), // 1: order_canceled_confirmation.OrderCanceledConfirmation
}
var file_order_canceled_confirmation_proto_depIdxs = []int32{
	0, // 0: order_canceled_confirmation.OrderCanceledConfirmation.Status:type_name -> order_canceled_confirmation.OrderCanceledStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_canceled_confirmation_proto_init() }
func file_order_canceled_confirmation_proto_init() {
	if File_order_canceled_confirmation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_canceled_confirmation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCanceledConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_canceled_confirmation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_canceled_confirmation_proto_goTypes,
		DependencyIndexes: file_order_canceled_confirmation_proto_depIdxs,
		EnumInfos:         file_order_canceled_confirmation_proto_enumTypes,
		MessageInfos:      file_order_canceled_confirmation_proto_msgTypes,
	}.Build()
	File_order_canceled_confirmation_proto = out.File
	file_order_canceled_confirmation_proto_rawDesc = nil
	file_order_canceled_confirmation_proto_goTypes = nil
	file_order_canceled_confirmation_proto_depIdxs = nil
}
