// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: market_depth.proto

package data

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MarketDepthPriceLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  uint64 `protobuf:"varint,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Volume uint64 `protobuf:"varint,2,opt,name=Volume,proto3" json:"Volume,omitempty"`
}

func (x *MarketDepthPriceLevel) Reset() {
	*x = MarketDepthPriceLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_depth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDepthPriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDepthPriceLevel) ProtoMessage() {}

func (x *MarketDepthPriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_market_depth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDepthPriceLevel.ProtoReflect.Descriptor instead.
func (*MarketDepthPriceLevel) Descriptor() ([]byte, []int) {
	return file_market_depth_proto_rawDescGZIP(), []int{0}
}

func (x *MarketDepthPriceLevel) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketDepthPriceLevel) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type MarketDepth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid        []*MarketDepthPriceLevel `protobuf:"bytes,1,rep,name=Bid,proto3" json:"Bid,omitempty"`
	Ask        []*MarketDepthPriceLevel `protobuf:"bytes,2,rep,name=Ask,proto3" json:"Ask,omitempty"`
	LastPrice  uint64                   `protobuf:"varint,3,opt,name=LastPrice,proto3" json:"LastPrice,omitempty"`
	LastVolume uint64                   `protobuf:"varint,4,opt,name=LastVolume,proto3" json:"LastVolume,omitempty"`
	Market     string                   `protobuf:"bytes,5,opt,name=Market,proto3" json:"Market,omitempty"`
}

func (x *MarketDepth) Reset() {
	*x = MarketDepth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_depth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDepth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDepth) ProtoMessage() {}

func (x *MarketDepth) ProtoReflect() protoreflect.Message {
	mi := &file_market_depth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDepth.ProtoReflect.Descriptor instead.
func (*MarketDepth) Descriptor() ([]byte, []int) {
	return file_market_depth_proto_rawDescGZIP(), []int{1}
}

func (x *MarketDepth) GetBid() []*MarketDepthPriceLevel {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *MarketDepth) GetAsk() []*MarketDepthPriceLevel {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *MarketDepth) GetLastPrice() uint64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *MarketDepth) GetLastVolume() uint64 {
	if x != nil {
		return x.LastVolume
	}
	return 0
}

func (x *MarketDepth) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

var File_market_depth_proto protoreflect.FileDescriptor

var file_market_depth_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x15, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x22, 0xc1, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x12, 0x2d, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x03, 0x42, 0x69, 0x64,
	0x12, 0x2d, 0x0a, 0x03, 0x41, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x03, 0x41, 0x73, 0x6b, 0x12,
	0x1c, 0x0a, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x4c, 0x61, 0x73, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_depth_proto_rawDescOnce sync.Once
	file_market_depth_proto_rawDescData = file_market_depth_proto_rawDesc
)

func file_market_depth_proto_rawDescGZIP() []byte {
	file_market_depth_proto_rawDescOnce.Do(func() {
		file_market_depth_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_depth_proto_rawDescData)
	})
	return file_market_depth_proto_rawDescData
}

var file_market_depth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_market_depth_proto_goTypes = []interface{}{
	(*MarketDepthPriceLevel)(nil), // 0: data.MarketDepthPriceLevel
	(*MarketDepth)(nil),           // 1: data.MarketDepth
}
var file_market_depth_proto_depIdxs = []int32{
	0, // 0: data.MarketDepth.Bid:type_name -> data.MarketDepthPriceLevel
	0, // 1: data.MarketDepth.Ask:type_name -> data.MarketDepthPriceLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_depth_proto_init() }
func file_market_depth_proto_init() {
	if File_market_depth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_depth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDepthPriceLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_depth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDepth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_depth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_depth_proto_goTypes,
		DependencyIndexes: file_market_depth_proto_depIdxs,
		MessageInfos:      file_market_depth_proto_msgTypes,
	}.Build()
	File_market_depth_proto = out.File
	file_market_depth_proto_rawDesc = nil
	file_market_depth_proto_goTypes = nil
	file_market_depth_proto_depIdxs = nil
}
